{
  "hash": "4c5df48389d851c795d33c3083c262c2",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Project Scheduling\n\n\n\n## Learning Objectives\n\nBy the end of this chapter you will be able to:\n\n1. **Read and build** a Gantt chart and explain what it adds over a network diagram.\n2. **Distinguish** the four precedence relationships (FS, FF, SS, SF) and use leads and lags.\n3. **Combine** PERT activity estimates into a project mean and standard deviation.\n4. **Calculate** the probability of finishing by a target date.\n5. **Compute** an activity's crash cost slope and build a **least-cost crashing** sequence.\n6. **Compare** crashing and fast-tracking, and state the risks of each.\n\n<details>\n<summary>Before we begin: a schedule is a promise --- how confident are you in it?</summary>\n\n\"The project finishes in 83 days\" sounds precise. Is that a date you would bet\nyour bonus on, or a coin flip? This chapter turns a single-number schedule into\na probability you can actually stand behind.\n\n</details>\n\n## Introduction: from a network to a calendar\n\nThe AON network from [Chapter 6](06-Network-Diagrams-and-AON.qmd) tells you the\nproject takes *N* days. The **schedule** puts those days on a calendar, assigns\nresources, and gives you something to track progress against. The classic tool\nis the **Gantt chart**, developed by Henry Gantt between 1910 and 1915 and used\nat scale for the first time on the **Hoover Dam** (1931--1936).\n\n::: {.callout-note}\n**Industry snapshot.** An automotive program's master schedule is a Gantt with\nthousands of rows rolled up to a one-page milestone view for the steering\ncommittee. A food-plant install schedule shows the trades stacked so the\nproject manager can see where two crews need the same space on the same day. A\ndefense schedule is baselined and every slip against it is reported.\n:::\n\n\n**3-Point Estimation for Project Schedule and Cost:** [https://www.youtube.com/watch?v=_YiAhMkBGbQ](https://www.youtube.com/watch?v=_YiAhMkBGbQ)\n\n## Gantt charts\n\nA Gantt chart is a **time-phased network**: it links each activity to a\ncalendar. Linked to a schedule, it also **tracks progress against the plan**.\nBenefits: easy to read; shows the network *and* the schedule together; supports\nupdating and control; useful for assigning resources; and easy to create.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ng <- data.frame(\n  task = c(\"A Design outer body\", \"B Design inner frame\", \"C Material selection\",\n           \"D Procure motor/controller\", \"E Wiring harness\",\n           \"F Prototype assembly\", \"G Drop & EMC test\", \"H Packaging & approvals\"),\n  start = c(0, 5, 5, 8, 15, 20, 30, 30),\n  dur   = c(5, 8, 3, 12, 5, 10, 8, 12),\n  crit  = c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE)\n)\ng$end <- g$start + g$dur\ng$task <- factor(g$task, levels = rev(g$task))\n\nggplot(g) +\n  geom_segment(aes(x = start, xend = end, y = task, yend = task, color = crit),\n               linewidth = 8, lineend = \"butt\") +\n  geom_text(aes(x = start + dur / 2, y = task, label = paste0(dur, \"d\")),\n            color = \"white\", fontface = \"bold\", size = 3.1 * diagram_text_scale) +\n  scale_color_manual(values = c(\"TRUE\" = \"#C0392B\", \"FALSE\" = \"#5DADE2\"),\n                     labels = c(\"TRUE\" = \"Critical path\", \"FALSE\" = \"Has float\"),\n                     name = NULL) +\n  labs(title = \"RC-vehicle sub-project schedule\", x = \"Project day\", y = NULL) +\n  theme_minimal() +\n  theme(\n    legend.position = \"top\",\n    plot.title = element_text(size = 14 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 10 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![A Gantt chart for the RC-vehicle sub-project. Bars are activities; the dark segments show the critical path. Arrows (implied by stacking) show that assembly cannot start until design finishes.](08-Project-Scheduling_files/figure-pdf/fig-gantt-08-1.pdf){#fig-gantt-08 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n## Precedence relationships\n\nMost dependencies are **finish-to-start**, but there are four:\n\n| Relationship | Meaning | Example |\n|---|---|---|\n| **Finish-to-Start (FS)** | B can't start until A finishes | Build the wall before you paint it |\n| **Finish-to-Finish (FF)** | B can't finish until A finishes | Can't finish editing until writing is finished |\n| **Start-to-Start (SS)** | B can't start until A starts (often simultaneous) | Start trimming edges when you start mowing |\n| **Start-to-Finish (SF)** | A starting triggers B finishing (rare) | The new shift starting ends the old shift |\n\nA **lead** lets a successor start early (overlap); a **lag** forces a wait\n(e.g. \"wait 2 days for the paint to cure\" is FS + 2-day lag).\n\n## Probabilistic scheduling with PERT\n\nA single duration hides uncertainty. Using three-point estimates\n(Chapter 6), for each activity:\n\n$$t_e = \\frac{o + 4m + p}{6}, \\qquad \\sigma = \\frac{p - o}{6}, \\qquad \\sigma^2 = \\left(\\frac{p - o}{6}\\right)^2$$\n\nFor the **project**, sum along the **critical path**:\n\n$$\\mu_{\\text{project}} = \\sum t_e, \\qquad \\sigma^2_{\\text{project}} = \\sum \\sigma^2, \\qquad \\sigma_{\\text{project}} = \\sqrt{\\sigma^2_{\\text{project}}}$$\n\n### Worked Example 1: project duration and its spread\n\nThe critical path is A--B--C--D--E with these three-point estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncp <- data.frame(\n  id = c(\"A\", \"B\", \"C\", \"D\", \"E\"),\n  o  = c(12, 7, 15, 9, 24),\n  m  = c(15, 10, 19, 13, 26),\n  p  = c(17, 13, 23, 16, 30)\n)\ncp$te  <- (cp$o + 4 * cp$m + cp$p) / 6\ncp$var <- ((cp$p - cp$o) / 6)^2\n\nmu    <- sum(cp$te)\nsigma <- sqrt(sum(cp$var))\n\ncp_show <- cp\ncp_show[c(\"te\", \"var\")] <- lapply(cp_show[c(\"te\", \"var\")], round, 2)\nprint(cp_show, row.names = FALSE)\ncat(sprintf(\"\\nProject mean duration : %.1f days\\n\", mu))\ncat(sprintf(\"Project variance      : %.2f\\n\", sum(cp$var)))\ncat(sprintf(\"Project std deviation : %.2f days\\n\", sigma))\ncat(sprintf(\"Rough 95%% range        : %.0f to %.0f days\\n\", mu - 2 * sigma, mu + 2 * sigma))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n id  o  m  p    te  var\n  A 12 15 17 14.83 0.69\n  B  7 10 13 10.00 1.00\n  C 15 19 23 19.00 1.78\n  D  9 13 16 12.83 1.36\n  E 24 26 30 26.33 1.00\n\nProject mean duration : 83.0 days\nProject variance      : 5.83\nProject std deviation : 2.42 days\nRough 95% range        : 78 to 88 days\n```\n\n\n:::\n:::\n\n\n### Try it yourself: probability of hitting a target date\n\nStandardize the target: $z = \\dfrac{\\text{target} - \\mu}{\\sigma}$, then read the\nnormal cumulative probability.\n\n```{webr-r}\n#| label: prob-on-time-08\nmu    <- 83.0     # from the worked example\nsigma <- 2.42\n\nfor (target in c(80, 83, 86, 88)) {\n  z <- (target - mu) / sigma\n  cat(sprintf(\"Finish by day %2d:  z = %+5.2f  ->  P = %4.1f%%\\n\",\n              target, z, 100 * pnorm(z)))\n}\n\ncat(\"\\nWhat target gives 90% confidence?\\n\")\ncat(sprintf(\"  day %.1f  (mu + %.2f x sigma)\\n\", mu + qnorm(0.90) * sigma, qnorm(0.90)))\n```\n\n<details>\n<summary>Why quote \"day 86 at 90 % confidence\" instead of \"day 83\"?</summary>\n\nDay 83 is the *mean* --- by definition you have only about a 50 % chance of\nmeeting it. Committing to the mean is committing to a coin flip. Adding a buffer\nto reach 85--90 % confidence is how you turn a schedule into a promise you can\nkeep, and it is the honest version of the \"padding\" problem from\n[Chapter 9](09-Cost-Estimation-and-Budgeting.qmd) --- one visible buffer at the\nproject level, not hidden padding in every task.\n\n</details>\n\n## Crashing the schedule\n\n**When** you crash: the initial schedule was too optimistic; the market wants\nthe product sooner; the project has slipped badly; or the contract rewards\nfinishing early / punishes finishing late.\n\n**How** you accelerate an activity: improve the productivity of existing\nresources (focus the team, review best practice); change the working method\n(swap drawing review for CAD model review); or add resources (overtime, extra\nshifts, expedited freight).\n\n::: {.callout-warning}\n**Caution on overtime.** Research on engineering work found optimal marginal\noutput at about **4 hours of overtime per week**; by **10 hours** of overtime the\n*marginal* extra output had fallen to **zero**. More hours is not more work.\n:::\n\nEvery activity has a **crash cost slope** --- the cost to buy back one time unit:\n\n$$\\text{slope} = \\frac{\\text{crash cost} - \\text{normal cost}}{\\text{normal time} - \\text{crash time}}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnormal_t <- 8; normal_c <- 14000\ncrash_t  <- 5; crash_c  <- 23000\nline <- data.frame(\n  t = c(crash_t, normal_t),\n  c = c(crash_c, normal_c)\n)\nggplot(line, aes(t, c)) +\n  geom_line(color = \"#2E86C1\", linewidth = 1.2) +\n  geom_point(size = 4, color = \"#1B4F72\") +\n  annotate(\"text\", x = normal_t, y = normal_c, label = \"Normal point\\n(8 wk, $14 000)\",\n           hjust = 1.1, size = 3.2 * diagram_text_scale, lineheight = 0.9) +\n  annotate(\"text\", x = crash_t, y = crash_c, label = \"Crash point\\n(5 wk, $23 000)\",\n           hjust = -0.1, size = 3.2 * diagram_text_scale, lineheight = 0.9) +\n  annotate(\"text\", x = 6.5, y = 15500,\n           label = \"slope = $9 000 / 3 wk\\n= $3 000 per week\",\n           size = 3.2 * diagram_text_scale, fontface = \"italic\", lineheight = 0.9) +\n  scale_y_continuous(labels = scales::dollar_format(big.mark = \" \")) +\n  scale_x_reverse(breaks = 5:8) +\n  labs(title = \"Time-cost trade-off for crashing\",\n       x = \"Activity duration (weeks) - shorter to the right\",\n       y = \"Activity cost\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 14 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 10 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![Time-cost trade-off for one activity. Between the normal and crash points, buying time gets steadily more expensive per day; past the crash point you cannot buy any more.](08-Project-Scheduling_files/figure-pdf/fig-time-cost-08-1.pdf){#fig-time-cost-08 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n### Try it yourself: least-cost crashing\n\nTo shorten the project, crash **critical-path** activities in **cheapest-slope-\nfirst** order, one time unit at a time, until you hit the target or run out of\ncrashable critical tasks.\n\n```{webr-r}\n#| label: crash-sequence-08\n# Critical-path activities: normal/crash time and cost.\nact <- data.frame(\n  id         = c(\"A\", \"F\", \"H\"),\n  normal_t   = c(9, 6, 8),\n  crash_t    = c(7, 5, 4),\n  normal_c   = c(5500, 4000, 3500),\n  crash_c    = c(7550, 9000, 7550)\n)\nact$slope     <- (act$crash_c - act$normal_c) / (act$normal_t - act$crash_t)\nact$max_crash <- act$normal_t - act$crash_t\n\ncat(\"Crash cost per day:\\n\")\nprint(act[c(\"id\", \"slope\", \"max_crash\")], row.names = FALSE)\n\ntarget_reduction <- 4          # days to remove from the project\norder_by_cost <- act[order(act$slope), ]\n\nremaining <- target_reduction\ntotal_cost <- 0\ncat(sprintf(\"\\nGoal: remove %d days, cheapest first\\n\", target_reduction))\nfor (i in seq_len(nrow(order_by_cost))) {\n  take <- min(remaining, order_by_cost$max_crash[i])\n  if (take <= 0) break\n  cost <- take * order_by_cost$slope[i]\n  total_cost <- total_cost + cost\n  remaining <- remaining - take\n  cat(sprintf(\"  crash %s by %d day(s) @ $%.0f/day = $%s\\n\",\n              order_by_cost$id[i], take, order_by_cost$slope[i],\n              format(cost, big.mark = \" \")))\n}\ncat(sprintf(\"\\nTotal crash cost for %d days: $%s\\n\",\n            target_reduction - remaining, format(total_cost, big.mark = \" \")))\nif (remaining > 0) cat(sprintf(\"Still %d day(s) short -- no cheap critical task left to crash.\\n\", remaining))\n```\n\n## Fast-tracking versus crashing\n\n| | **Crashing** | **Fast-tracking** |\n|---|---|---|\n| Method | Add resources (overtime, staff, expediting) | Overlap tasks that were sequential |\n| Cost | Always adds cost | Little or no added cost |\n| Risk | Diminishing returns; overtime burnout | Rework if the predecessor changes after the successor started |\n\nBoth only help on the **critical path**, and after either one you must\n**re-check the network** --- the critical path can move.\n\n## Key Takeaways\n\n- A **Gantt chart** puts the network on a calendar and lets you track progress; it shows activities, dependencies, and resources at once.\n- Four precedence types: **FS** (default), **FF**, **SS**, **SF** --- with **leads** (overlap) and **lags** (forced wait).\n- PERT project: $\\mu = \\sum t_e$ and $\\sigma = \\sqrt{\\sum \\sigma^2}$ along the **critical path**. The mean is a ~50 % date.\n- Probability of on-time: $z = (\\text{target} - \\mu)/\\sigma$, then the normal CDF. Commit to an ~85--90 % date, not the mean.\n- **Crash cost slope** $=$ (crash cost − normal cost) / (normal time − crash time). Crash **critical tasks, cheapest slope first**.\n- **Crashing** buys time with money; **fast-tracking** buys it with rework risk. Re-check the critical path after either.\n\n## Practice Problems\n\n<details>\n<summary>Problem 1: Least-cost crash to a deadline</summary>\n\nProject critical path A--F--H, currently 23 weeks; the contract needs 20. Crash\ndata: A \\$513/wk (max 4 wk), F \\$1 500/wk (max 1 wk), H \\$950/wk (max 2 wk).\nFind the least-cost way to remove 3 weeks.\n\n**Solution.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrash <- data.frame(\n  id = c(\"A\", \"F\", \"H\"),\n  slope = c(513, 1500, 950),\n  max = c(4, 1, 2)\n)\nneed <- 3\ncrash <- crash[order(crash$slope), ]\nleft <- need; cost <- 0\nfor (i in seq_len(nrow(crash))) {\n  take <- min(left, crash$max[i]); if (take <= 0) break\n  cost <- cost + take * crash$slope[i]; left <- left - take\n  cat(sprintf(\"Crash %s by %d wk @ $%d = $%s\\n\", crash$id[i], take, crash$slope[i],\n              format(take * crash$slope[i], big.mark = \" \")))\n}\ncat(sprintf(\"Total: $%s for %d weeks\\n\", format(cost, big.mark = \" \"), need - left))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCrash A by 3 wk @ $513 = $1 539\nTotal: $1 539 for 3 weeks\n```\n\n\n:::\n:::\n\n\nCrash A by 3 weeks for \\$1 539 --- far cheaper than touching F or H.\n\n</details>\n\n<details>\n<summary>Problem 2: Confidence in a date</summary>\n\nA project's critical path has $\\mu = 60$ days and $\\sigma = 4$ days. The customer\nwants delivery in 64 days.\n\n(a) What is the probability of meeting day 64? (b) What date should you commit to\nfor 95 % confidence?\n\n**Solution.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- 60; sigma <- 4\ncat(sprintf(\"P(finish by day 64) = %.1f%%\\n\", 100 * pnorm((64 - mu) / sigma)))\ncat(sprintf(\"95%% confident date  = day %.1f\\n\", mu + qnorm(0.95) * sigma))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(finish by day 64) = 84.1%\n95% confident date  = day 66.6\n```\n\n\n:::\n:::\n\n\n(a) ~84 %. (b) Day 66.6 --- commit to day 67.\n\n</details>\n\n<details>\n<summary>Problem 3 (discussion): crash or fast-track the RC-vehicle launch?</summary>\n\nThe retailer moves the launch three weeks earlier. Design is on the critical\npath and is followed by prototype assembly (also critical). You could add a\nsecond designer and pay overtime (crash), or start building the frame jig from\nthe released frame drawings while the body design is still being finalized\n(fast-track). Which, and why?\n\n**Discussion points.** Fast-tracking the jig against the *frame* drawings is\nlow-cost and reasonably safe *if* the frame design is stable --- but if the body\ndesign forces a late frame change, the jig is rework. Crashing design with a\nsecond modeller adds cost and has coordination overhead (two people on one\nmodel), but no rework risk. A common answer: fast-track the clearly stable parts,\ncrash the rest, and hold a contingency for the rework risk you accepted.\n\n</details>\n\n## Further Resources\n\n\n**PERT / Three-Point Estimation Technique:** [https://www.youtube.com/watch?v=6B7Qtc3rrQ4](https://www.youtube.com/watch?v=6B7Qtc3rrQ4)\n\n\n\n**Forward and Backward Pass -> Project Duration and Critical Path:** [https://www.youtube.com/watch?v=4oDLMs11Exs](https://www.youtube.com/watch?v=4oDLMs11Exs)\n",
    "supporting": [
      "08-Project-Scheduling_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}