{
  "hash": "1b66a41be8d40cbf8cffe1b4baf8a696",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Project Closeout and Termination\n\n\n\n## Learning Objectives\n\nBy the end of this chapter you will be able to:\n\n1. **State** what project termination provides and distinguish its types --- extinction, addition, integration, starvation.\n2. **Work through** the seven elements of closeout.\n3. **Explain** what commonly prevents effective closeout.\n4. **Recognize** the early warning signs of project failure.\n5. **Apply** the cancel/continue decision using sunk cost, cost-to-complete, and remaining benefit.\n6. **Reconcile** a completed project: planned vs. actual schedule and cost.\n7. **Draw** the common lessons from famous project failures.\n\n<details>\n<summary>Before we begin: which is harder --- starting a project or finishing one?</summary>\n\nStarting has energy and a blank page. Finishing has a tired team, a client\neager to move on, and a next project already calling. Closeout is *\"the most\ndifficult phase to complete effectively and has the most impact on future\nprojects.\"*\n\n</details>\n\n## Introduction: planning for extinction\n\nA defining feature of a project is a **finite life**. When you plan a project,\nyou are also *\"planning for its extinction.\"* The RC-vehicle prototype project\nwill end --- and if it succeeds, its team likely rolls straight into supporting\nthe 100 000-unit production run. That is a real, named way for a project to end,\nnot an afterthought.\n\n**Project termination** provides for:\n\n- **Acceptance** of the project by the sponsor\n- **Completion** of the project records\n- **Final revision and issue** of documentation to its as-built condition\n- **Retention** of the essential documentation --- above all, the **lessons learned**\n\n\n**Unlock the Secrets to Easy Project Closure (Association for Project Management):** [https://www.youtube.com/watch?v=0HVtpstAT7M](https://www.youtube.com/watch?v=0HVtpstAT7M)\n\n## Types of termination\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntt <- data.frame(\n  type = c(\"Extinction\", \"Addition\", \"Integration\", \"Starvation\"),\n  x = 1:4,\n  desc = c(\"Stopped -- success or failure.\\nBudget audited, team\\nreassigned, assets dispersed.\",\n           \"Institutionalized as a\\npermanent part of the\\norganization (project team\\n-> production support team).\",\n           \"Resources and team\\nreabsorbed into the existing\\nstructure / functional\\ndepartments.\",\n           \"Budget quietly cut until\\nthe project cannot survive.\\nOften political -- a 'pet\\nproject' kept on the books.\")\n)\nggplot(tt, aes(x, 0)) +\n  geom_label(aes(label = type), nudge_y = 0.55, size = 3.6 * diagram_text_scale,\n             fontface = \"bold\", fill = c(\"#A9DFBF\", \"#A9DFBF\", \"#A9DFBF\", \"#F5B7B1\"),\n             label.size = 0) +\n  geom_text(aes(label = desc), size = 2.6 * diagram_text_scale, lineheight = 0.95,\n            vjust = 1) +\n  coord_cartesian(xlim = c(0.4, 4.6), ylim = c(-1.1, 1)) +\n  theme_void()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The `label.size` argument of `geom_label()` is deprecated as of ggplot2 3.5.0.\ni Please use the `linewidth` argument instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Four ways a project ends. Extinction, addition, and integration are normal; starvation is a slow, deliberate neglect.](13-Project-Closeout-and-Termination_files/figure-pdf/fig-termination-types-13-1.pdf){#fig-termination-types-13 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n- **Extinction** --- the project is stopped, successfully or not. The final budget is audited, team members get new assignments, material assets are dispersed or transferred per company/contract terms.\n- **Addition** --- a successful project is made a **formal part of the organization**. An automaker that has launched a new vehicle keeps the project team on as a **production support team**.\n- **Integration** --- the team and resources are **reabsorbed** into the existing structure. Common but complicated --- and organizations often **lose key people** here, who leave for fresh project challenges rather than return to the old department.\n- **Starvation** --- not really a termination act but *\"a willful form of neglect\"*: the budget is decreased slowly until the project cannot remain viable. Kept \"on the books\" for political reasons, a powerful sponsor's pet project, or so it can be reactivated when budgets recover.\n\n## The seven elements of closeout\n\n\n::: {#tbl-closeout-13 .cell}\n\n```{.r .cell-code}\nclose <- data.frame(\n  `#` = 1:7,\n  Element = c(\"Verify scope\", \"Closeout contracts\", \"Closeout administration\",\n              \"Conduct a lessons-learned review\", \"Build a project history file\",\n              \"Create the final project report\", \"Celebrate success\"),\n  What = c(\n    \"Compare to the original scope statement; resolve discrepancies; confirm every deliverable is present; assess customer satisfaction.\",\n    \"Resolve all open issues with the customer; return or destroy proprietary documents as directed; receive final payments. The client is a future customer -- leave them feeling good.\",\n    \"Return all loaned personnel; complete performance evaluations.\",\n    \"Survey everyone who was on the project; hold the meeting; be critical -- dissect what went wrong and why, not what went right.\",\n    \"Document planned vs. actual schedule and cost (with reasons), approved changes, meeting minutes, WBS, risk plans, subcontractor and customer-satisfaction records, reviews.\",\n    \"Document overall success, project organization, recommended changes for similar projects, techniques used to overcome obstacles, strengths and weaknesses, team recommendations, projected vs. actual impact, team members.\",\n    \"Involve everyone who played a role; hold it away from the workplace; personally recognize outstanding performers. This is about the team, not the PM.\"\n  ),\n  check.names = FALSE\n)\nknitr::kable(close, align = c(\"c\", \"l\", \"l\"),\n             caption = \"The seven elements of project closeout.\") |>\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n                            full_width = FALSE) |>\n  kableExtra::column_spec(2, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{c>{}ll}\n\\caption{\\label{tab:tbl-closeout-13}The seven elements of project closeout.}\\\\\n\\toprule\n\\# & Element & What\\\\\n\\midrule\n1 & \\textbf{Verify scope} & Compare to the original scope statement; resolve discrepancies; confirm every deliverable is present; assess customer satisfaction.\\\\\n2 & \\textbf{Closeout contracts} & Resolve all open issues with the customer; return or destroy proprietary documents as directed; receive final payments. The client is a future customer -- leave them feeling good.\\\\\n3 & \\textbf{Closeout administration} & Return all loaned personnel; complete performance evaluations.\\\\\n4 & \\textbf{Conduct a lessons-learned review} & Survey everyone who was on the project; hold the meeting; be critical -- dissect what went wrong and why, not what went right.\\\\\n5 & \\textbf{Build a project history file} & Document planned vs. actual schedule and cost (with reasons), approved changes, meeting minutes, WBS, risk plans, subcontractor and customer-satisfaction records, reviews.\\\\\n\\addlinespace\n6 & \\textbf{Create the final project report} & Document overall success, project organization, recommended changes for similar projects, techniques used to overcome obstacles, strengths and weaknesses, team recommendations, projected vs. actual impact, team members.\\\\\n7 & \\textbf{Celebrate success} & Involve everyone who played a role; hold it away from the workplace; personally recognize outstanding performers. This is about the team, not the PM.\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### What prevents effective closeout\n\n- Getting the project **signed off** discourages the other closeout activities.\n- The **assumed urgency** of every project pressures the team to cut corners on the back end.\n- Closeout is given **low priority** and easily ignored.\n- **Lessons learned** is dismissed as a bookkeeping chore.\n- People assume that because every project is unique, **carryover is minimal**.\n- People just want to **move on** to the next challenge.\n\n## Project failure\n\n**Failure** = the project does not deliver what was required, judged against the\n**acceptance criteria** of the sponsor and customer, and can be triggered by\nchanges in **scope, cost, or time**.\n\n**Early warning signs:**\n\n- Lack of viable **commercial objectives**\n- Lack of sufficient **decision-making authority**\n- **Market volatility**\n- **Low priority** assigned to the project\n\n**When to consider cancelling:**\n\n- Costs **exceed the business benefits**\n- The project no longer meets **strategic-fit** criteria\n- **Deadlines** keep being missed\n- **Technology evolves** beyond the project's scope\n\n### Worked Example 1: continue or cancel?\n\nA project has already spent **\\$480 000** (sunk). Finishing it needs another\n**\\$260 000**. The product, if delivered, is now worth an estimated\n**\\$300 000** in benefit --- the market moved while you were building.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsunk            <- 480000     # already spent -- IRRELEVANT to the decision\ncost_to_finish  <- 260000\nremaining_benefit <- 300000\n\nnet_if_continue <- remaining_benefit - cost_to_finish\ncat(sprintf(\"Sunk cost (ignore it)        : $%s\\n\", format(sunk, big.mark = \" \")))\ncat(sprintf(\"Cost to finish               : $%s\\n\", format(cost_to_finish, big.mark = \" \")))\ncat(sprintf(\"Benefit if finished          : $%s\\n\", format(remaining_benefit, big.mark = \" \")))\ncat(sprintf(\"Net from *here*              : $%s\\n\", format(net_if_continue, big.mark = \" \")))\ncat(ifelse(net_if_continue > 0,\n           \"\\n-> CONTINUE: the remaining benefit still beats the remaining cost.\\n\",\n           \"\\n-> CANCEL: finishing loses money from here, regardless of the $480k already gone.\\n\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSunk cost (ignore it)        : $480 000\nCost to finish               : $260 000\nBenefit if finished          : $3e+05\nNet from *here*              : $40 000\n\n-> CONTINUE: the remaining benefit still beats the remaining cost.\n```\n\n\n:::\n:::\n\n\nThe \\$480 000 is a **sunk cost** --- it is spent whether you continue or not, so\nit must not enter the decision. From here, spending \\$260 000 to get \\$300 000 is\nstill worth \\$40 000. (The sunk-cost fallacy --- \"we've come too far to stop\" ---\nis what keeps doomed projects alive.)\n\n### Try it yourself: the cancel decision under uncertainty\n\n```{webr-r}\n#| label: cancel-decision-13b\nsunk           <- 480000\ncost_to_finish <- 260000\n\n# The remaining benefit is uncertain -- try a range of market outcomes.\nfor (benefit in c(150000, 250000, 300000, 400000)) {\n  net <- benefit - cost_to_finish\n  verdict <- ifelse(net > 0, \"CONTINUE\", \"CANCEL\")\n  cat(sprintf(\"If remaining benefit = $%s  ->  net from here $%+d  ->  %s\\n\",\n              format(benefit, big.mark = \" \"), net, verdict))\n}\ncat(sprintf(\"\\nBreak-even benefit: $%s. Below that, finishing destroys value\\n\",\n            format(cost_to_finish, big.mark = \" \")))\ncat(\"-- no matter how much has already been spent.\\n\")\n```\n\n## Lessons from spectacular failures\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nov <- data.frame(\n  project = c(\"Channel Tunnel\", \"Canadian Firearms Registry\", \"Project Taurus (LSE)\"),\n  multiple = c(1.85, 8.4, 132)\n)\nov$project <- factor(ov$project, levels = rev(ov$project))\nggplot(ov, aes(multiple, project)) +\n  geom_col(fill = \"#C0392B\", width = 0.6) +\n  geom_text(aes(label = paste0(multiple, \"x\")), hjust = -0.2,\n            size = 3.8 * diagram_text_scale) +\n  scale_x_continuous(trans = \"log10\", limits = c(1, 300),\n                     breaks = c(1, 2, 5, 10, 30, 100, 300),\n                     expand = expansion(mult = c(0, 0.05))) +\n  labs(title = \"Final cost as a multiple of the original budget (log scale)\",\n       x = \"Overrun multiple\", y = NULL) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 13 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 10 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![Cost overrun as a multiple of the original budget for three well-documented failures. Project Taurus (London Stock Exchange) ran to roughly 132 times its first budget before being abandoned after 11 years.](13-Project-Closeout-and-Termination_files/figure-pdf/fig-overruns-13-1.pdf){#fig-overruns-13 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n- **Bank of America \"MasterNet\"** (1984) --- trust-department automation. Over budget by \\$35M, rising toward \\$80M; a 1988 failure meant loss of control over billions in trust accounts, all eventually recovered, but the **entire 255-person department was let go** as depositors fled. *Cause: scope and complexity understood far too late.*\n- **Future Imagery Architecture** (US spy satellites, 1997) --- bid won by a contractor that had never built an imaging satellite; internal estimate already predicted a \\$4B overrun. **Testing was cut to save money**; a subcontractor's undisclosed manufacturing change caused gyroscope defects undiscovered for three years; costs reached ~\\$18B by 2005. *Cause: unqualified bidder, cut testing, uncontrolled change.*\n- **Canadian Firearms Registry** (1995) --- estimated at \\$119M to implement; a 2002 audit projected ~**\\$1B**. *Causes: scope not understood, no plan for inter-agency cooperation, inconsistent data criteria, cost cover-up, no measurement of whether the registry actually worked.*\n- **Channel Tunnel** (budgeted 1979, opened 1994, one year late) --- final cost roughly **double** the original budget.\n- **Project Taurus** (London Stock Exchange paperless settlement, 1983) --- abandoned after **11 years** at ~**132 times** its original budget after switching to an incompatible US system that clashed with British finance law.\n\n**The recurring threads:** scope not truly understood; optimism and cost\nconcealment; cutting testing to save money; no plan for the interfaces between\norganizations; and pressing on past every off-ramp because of sunk cost.\n\n### Try it yourself: the final project reconciliation\n\n```{webr-r}\n#| label: reconciliation-13\n# Planned vs actual for the RC-vehicle prototype project at closeout.\nplanned_weeks <- 30;      actual_weeks <- 34\nplanned_cost  <- 620000;  actual_cost  <- 703000\nplanned_scope_items <- 12; delivered_items <- 12   # all deliverables met\n\nsched_var_pct <- 100 * (actual_weeks - planned_weeks) / planned_weeks\ncost_var_pct  <- 100 * (actual_cost - planned_cost) / planned_cost\n\ncat(sprintf(\"Schedule : planned %d wk, actual %d wk  (%+.1f%%)\\n\",\n            planned_weeks, actual_weeks, sched_var_pct))\ncat(sprintf(\"Cost     : planned $%s, actual $%s  (%+.1f%%)\\n\",\n            format(planned_cost, big.mark = \" \"),\n            format(actual_cost, big.mark = \" \"), cost_var_pct))\ncat(sprintf(\"Scope    : %d of %d deliverables accepted\\n\",\n            delivered_items, planned_scope_items))\n\nverdict <- if (delivered_items == planned_scope_items && cost_var_pct < 20 && sched_var_pct < 20)\n  \"SUCCESS with overruns -- document the causes in the history file and lessons learned.\"\nelse \"TROUBLED -- the lessons-learned review is the priority deliverable.\"\ncat(\"\\n\", verdict, \"\\n\", sep = \"\")\n```\n\n## Closing out the RC-vehicle project\n\n- **Verify scope** against the signed scope statement: all body options delivered, drop and EMC tests passed, compliance approvals in hand, retailer satisfaction confirmed.\n- **Closeout contracts**: settle final invoices with MCS/Paragon and the carbon-fibre supplier; return the customer's proprietary artwork.\n- **Administration**: return the borrowed design engineers and millwrights to their functional managers with completed performance reviews.\n- **Lessons learned**: the new-line learning curve and the unproven-supplier risk are the two entries that matter most for the next program.\n- **Termination by addition**: the prototype team transitions into the **production support team** for the 100 000-unit run.\n- **Celebrate** --- away from the plant, with everyone who contributed.\n\n## Key Takeaways\n\n- Termination provides **sponsor acceptance, complete records, as-built documentation, and retained lessons learned.**\n- Types: **extinction** (stopped), **addition** (becomes permanent), **integration** (reabsorbed), **starvation** (slow deliberate neglect).\n- Work the **seven elements**: verify scope, close contracts, close administration, lessons learned, history file, final report, celebrate.\n- Closeout fails because sign-off feels like \"done\", the next project is louder, and lessons learned is treated as bookkeeping. Resist all three.\n- **Cancel** when the **cost to complete exceeds the remaining benefit** --- the money already spent is **sunk** and irrelevant to that decision.\n- Famous failures share the same causes: **scope not understood, cost concealed, testing cut, interfaces unplanned, sunk-cost momentum.**\n\n## Practice Problems\n\n<details>\n<summary>Problem 1: Sunk cost trap</summary>\n\nA project has consumed \\$1.2M of a \\$1.5M budget. Finishing needs \\$500 000\n(the last \\$300 000 of budget plus a \\$200 000 overrun). The delivered product\nis now worth \\$350 000. The sponsor says \"we've spent \\$1.2M --- we can't stop\nnow.\" Evaluate.\n\n**Solution.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncost_to_finish <- 500000\nremaining_benefit <- 350000\ncat(sprintf(\"Net from here: $%s - $%s = $%s\\n\",\n            format(remaining_benefit, big.mark = \" \"),\n            format(cost_to_finish, big.mark = \" \"),\n            format(remaining_benefit - cost_to_finish, big.mark = \" \")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNet from here: $350 000 - $5e+05 = $-150 000\n```\n\n\n:::\n:::\n\n\nFinishing turns \\$500 000 of new spend into \\$350 000 of value --- a \\$150 000\nloss **from today**. The \\$1.2M is gone either way. Cancel (or de-scope until\nthe remaining cost drops below \\$350 000). \"We can't stop now\" is the sunk-cost\nfallacy.\n\n</details>\n\n<details>\n<summary>Problem 2: Which termination type?</summary>\n\n1. The RC-vehicle prototype team becomes the production line's support team. → **Addition.**\n2. A cancelled R&D project's engineers return to the design department. → **Integration.**\n3. A failed pilot is shut down, its budget audited, its test rig sold. → **Extinction.**\n4. A VP's favourite project keeps a \\$1/year budget so it stays \"active\" on paper. → **Starvation.**\n\n</details>\n\n<details>\n<summary>Problem 3 (discussion): the team wants to skip lessons learned</summary>\n\nThe RC-vehicle project delivered late and over budget but the product passed.\nThe exhausted team wants to skip the lessons-learned review and start on the\nproduction ramp. As PM, what do you do and why?\n\n**Discussion points.** This is exactly the moment the review matters most --- a\ntroubled project is where the carryover value is highest, and the next program\nwill hit the *same* new-line learning curve and *same* supplier risk. Keep it\nshort and structured, focus on **what went wrong and why** (not blame), capture\n2--3 concrete, assigned actions, and put it in the history file before the team\ndisperses and the memory fades. Skipping it guarantees the next project repeats\nthe overrun.\n\n</details>\n\n## Further Resources\n\n\n**What Is Project Management? (Association for Project Management):** [https://www.youtube.com/watch?v=Jk-JwtScIlw](https://www.youtube.com/watch?v=Jk-JwtScIlw)\n",
    "supporting": [
      "13-Project-Closeout-and-Termination_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}