{
  "hash": "961003131c4d1454e4f0b6430e917711",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Risk Management\n\n\n\n## Learning Objectives\n\nBy the end of this chapter you will be able to:\n\n1. **Distinguish** risk from uncertainty, and threats from opportunities.\n2. **Classify** a risk and write a well-formed risk statement.\n3. **Run** a qualitative analysis with a probability--impact matrix.\n4. **Compute** expected monetary value (EMV) and solve a simple decision tree.\n5. **Select** a response strategy: accept, minimize, share, transfer, or reserve.\n6. **Size** a contingency reserve and distinguish task contingency from managerial contingency.\n7. **Explain** how FMEA supports project risk management.\n\n<details>\n<summary>Before we begin: name one thing that could sink the RC-vehicle project</summary>\n\nNow: how likely is it, and how bad would it be? You just did qualitative risk\nanalysis. The rest of this chapter makes it systematic.\n\n</details>\n\n## Introduction: the known unknowns\n\nThe RC-vehicle brief is a risk register waiting to be written. One candidate\nmotor supplier is **unproven** and its staff are **negotiating a first labour\ncontract**. The carbon-fibre supplier is **mid-restructuring** after a foreign\nacquisition. Choosing a **new assembly line** brings a **learning curve**. None\nof these is a certainty --- but each is *identifiable*, and that is exactly what\nmakes it a **risk** rather than an uncertainty.\n\n> **Risk** = the probability or threat of loss, injury, or any negative\n> occurrence caused by internal or external vulnerabilities, that **can be\n> reduced by preemptive action**.\n>\n> An **uncertainty** is when *neither* the probability *nor* the mode of\n> occurrence is known. If you do not know about it, you cannot act on it.\n\nThe core equation:\n\n$$\\text{Risk} = \\text{Probability of event} \\times \\text{Impact of event}$$\n\nProbability is usually a percentage; impact is dollars or schedule delay. **Risk\nand opportunity are mirror images** --- an opportunity is an unforeseen event with\na *positive* outcome, handled with the same tools for the opposite end.\n\n::: {.callout-note}\n**Industry snapshot.** Aircraft makers such as Bombardier **minimize** part risk\nby forcing every significant supplier into direct contact with their quality\ndepartment and auditing their processes. The European Space Agency and Airbus\n**share** the risk of a new airframe across nations because no one country can\ncarry it. A fixed-price defense contract **transfers** budget-overrun risk to\nthe vendor.\n:::\n\n\n<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;\">\n  <iframe\n    style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\"\n    src=\"https://www.youtube.com/embed/dD-Vygp_MiM\"\n    title=\"Expected Monetary Value (EMV) Explained Simply (Online PM Courses)\"\n    frameborder=\"0\"\n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n    referrerpolicy=\"strict-origin-when-cross-origin\"\n    allowfullscreen>\n  </iframe>\n</div>\n\n## The four-stage process\n\n1. **Risk identification** --- determine the specific risk factors that can reasonably be expected to affect the project.\n2. **Analysis of probability and consequences** --- how likely, and how bad.\n3. **Risk mitigation strategies** --- steps to reduce the impact of the risks judged threatening enough to act on.\n4. **Control and documentation** --- track the risks and build a **knowledge base** for future projects from the lessons learned.\n\n## Risk identification and classification\n\nSort each identified risk into a class. A common (not exhaustive) list:\n\n- **Financial** --- material price moves, currency, budget cuts\n- **Technology** --- unproven design or process\n- **Resources** --- key people, equipment availability\n- **Schedule** --- dependency slips, long lead times\n- **Weather**, **Political**, **Environmental**\n\nTechniques: structured **brainstorming**, **interviewing** to get optimistic /\nmost-likely / pessimistic views of an event, **probability distributions** to\nrepresent uncertain outcomes, and **expert judgment** to validate.\n\n## Qualitative analysis: the probability--impact matrix\n\nPlot each risk by **likelihood** (x-axis) and **impact** (y-axis). The\ntop-right is **red** (mitigation planned in advance), the middle band\n**yellow** (team decides whether to plan), the bottom-left **green** (just stay\naware).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrid <- expand.grid(prob = 1:5, impact = 1:5)\ngrid$score <- grid$prob * grid$impact\ngrid$zone <- cut(grid$score, c(0, 6, 12, 25),\n                 labels = c(\"Green\", \"Yellow\", \"Red\"))\n\nrisks <- data.frame(\n  risk = c(\"Unproven supplier can't deliver\", \"Carbon-fibre plant disruption\",\n           \"New line learning curve overruns\", \"Labour action at supplier\",\n           \"Steel price spike\", \"Minor drawing errors\"),\n  prob = c(3, 3, 4, 2, 3, 4),\n  impact = c(5, 4, 3, 5, 2, 1)\n)\n\nggplot(grid, aes(prob, impact)) +\n  geom_tile(aes(fill = zone), color = \"white\", linewidth = 1) +\n  scale_fill_manual(values = c(Green = \"#A9DFBF\", Yellow = \"#F9E79F\", Red = \"#F5B7B1\"),\n                    name = \"Zone\") +\n  geom_point(data = risks, aes(prob, impact), inherit.aes = FALSE,\n             size = 3, color = \"#1B4F72\") +\n  geom_text(data = risks, aes(prob, impact, label = risk), inherit.aes = FALSE,\n            size = 2.7 * diagram_text_scale, vjust = -1, hjust = 0.5) +\n  scale_x_continuous(breaks = 1:5, labels = c(\"Very low\", \"Low\", \"Medium\", \"High\", \"Very high\")) +\n  scale_y_continuous(breaks = 1:5, labels = c(\"Negligible\", \"Minor\", \"Moderate\", \"Major\", \"Severe\")) +\n  labs(title = \"Probability x Impact\", x = \"Probability\", y = \"Impact\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 14 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 9.5 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![Probability-impact matrix for the RC-vehicle project. Red-zone risks (unproven supplier failure, carbon-fibre disruption) get a written mitigation plan before anything goes wrong.](07-Risk-Management_files/figure-html/fig-pi-matrix-07-1.png){#fig-pi-matrix-07 fig-align='center' width=912}\n:::\n:::\n\n\n## Quantitative analysis\n\nTools: **sensitivity analysis** (which risks move the outcome most),\n**expected monetary value** (the probability-weighted average outcome),\n**decision trees** (lay out choices and chance events), and **Monte Carlo**\nsimulation (run the network thousands of times with sampled durations/costs).\n\n### Worked Example 1: EMV of a single risk\n\nThe \"new assembly line learning curve\" risk: a **40 %** chance it adds\n**\\$120 000** of rework and overtime; otherwise \\$0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_occurs <- 0.40\nimpact   <- 120000\n\nemv <- p_occurs * impact + (1 - p_occurs) * 0\ncat(sprintf(\"EMV of this risk: 0.40 x $%s = $%s\\n\",\n            format(impact, big.mark = \" \"), format(emv, big.mark = \" \")))\ncat(\"This is the amount you would budget in a risk reserve to 'cover' this one risk on average.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEMV of this risk: 0.40 x $120 000 = $48 000\nThis is the amount you would budget in a risk reserve to 'cover' this one risk on average.\n```\n\n\n:::\n:::\n\n\n### Try it yourself: decision tree --- buy the copper now or later?\n\nYou need **750 lb of copper** for the RC-vehicle wiring harness tooling. Buy it\n**now** and pay **\\$100** storage, or buy it **later** at the summer price ---\nwhich is **\\$5.58/lb with 90 % probability**, or **\\$4.50/lb with 10 %\nprobability**.\n\n```{webr-r}\n#| label: decision-tree-07\nlb <- 750\nstorage <- 100\n\n# Branch: buy now (price locked, pay storage)\nbuy_now <- 5.58 * lb + storage\n\n# Branch: buy later (two chance outcomes)\np_high <- 0.90; price_high <- 5.58\np_low  <- 0.10; price_low  <- 4.50\nbuy_later <- p_high * (price_high * lb) + p_low * (price_low * lb)\n\ncat(sprintf(\"EMV, buy now  : $%.2f\\n\", buy_now))\ncat(sprintf(\"EMV, buy later: 0.90 x $%.2f + 0.10 x $%.2f = $%.2f\\n\",\n            price_high * lb, price_low * lb, buy_later))\ncat(sprintf(\"\\nChoose: %s  (saves $%.2f on average)\\n\",\n            ifelse(buy_later < buy_now, \"BUY LATER\", \"BUY NOW\"),\n            abs(buy_now - buy_later)))\n```\n\n<details>\n<summary>What would flip the decision?</summary>\n\nRaise the probability of the low summer price, widen the price gap, or cut the\nstorage cost toward zero and \"buy later\" wins by more. Push storage cost up\n(a bonded warehouse, insurance, spoilage) or make the high price nearly\ncertain and \"buy now\" wins. A decision tree makes the tipping point explicit\ninstead of leaving it to gut feel.\n\n</details>\n\n## Response strategies\n\n| Strategy | What it means | Example on our project |\n|---|---|---|\n| **Accept** | The risk is minor or unlikely enough to live with | Small drawing errors --- caught in review, low cost |\n| **Minimize** | Reduce probability or impact | Audit the unproven supplier; put their staff in contact with your quality team |\n| **Share** | Split the risk (and reward) with a partner | Co-develop the new control system with the supplier under a shared-savings deal |\n| **Transfer** | Shift the risk to another party | Fixed-price contract (vendor eats overruns); **liquidated damages** for non-performance |\n| **Contingency reserve** | Set aside funds/time for the risk if it hits | 10--15 % reserve against the carbon-fibre and learning-curve risks |\n| **Other** | Anything else fit for the situation | Dual-source the motor; pre-qualify a backup |\n\nFor **opportunities**, the mirror strategies are **exploit, share, enhance,** and\n**accept**.\n\n## Contingency reserves\n\nTwo kinds:\n\n- **Task (project) contingency** --- offsets overruns on individual tasks/work packages. **Managed by the project manager.** As work completes, reserve for finished tasks is released and cannot be reused.\n- **Managerial contingency** --- a project-level buffer for scope changes forced by the customer, \"acts of God,\" and other unforeseeable events. **Managed by senior management, not the PM.**\n\nIn construction it is common to set aside **10--15 %** of the price. Other\nindustries resist it --- the customer may read a visible reserve as a sign of\npoor planning.\n\n### Try it yourself: does the mitigation pay for itself?\n\n```{webr-r}\n#| label: mitigation-value-07\n# Risk: unproven supplier fails to deliver on time.\np_fail_no_action <- 0.35\nimpact_if_fail   <- 260000       # expedite alternative source + line downtime\n\n# Mitigation: pre-qualify a backup supplier now.\nmitigation_cost  <- 22000\np_fail_with_action <- 0.10       # backup ready -> failure much less damaging\nimpact_with_action <- 90000      # switch to backup, smaller hit\n\nemv_before <- p_fail_no_action * impact_if_fail\nemv_after  <- mitigation_cost + p_fail_with_action * impact_with_action\n\ncat(sprintf(\"EMV, do nothing        : $%s\\n\", format(round(emv_before), big.mark = \" \")))\ncat(sprintf(\"EMV, pre-qualify backup : $%s  (incl. $%s spent now)\\n\",\n            format(round(emv_after), big.mark = \" \"),\n            format(mitigation_cost, big.mark = \" \")))\ncat(sprintf(\"\\nExpected saving from acting: $%s\\n\",\n            format(round(emv_before - emv_after), big.mark = \" \")))\n```\n\n## FMEA as a risk tool\n\n**Failure Mode and Effects Analysis** is often the first step of a reliability\nstudy: review as many components, assemblies, and subsystems as possible to\nidentify **failure modes** (what can fail and how), their **causes**, and their\n**effects** (the consequences). It is a structured, bottom-up way to surface\ntechnical risks before they reach the customer --- and it feeds the same\nprobability--impact thinking used above (in FMEA terms, a **risk priority\nnumber** combining severity, occurrence, and detection).\n\n## Key Takeaways\n\n- A **risk** is identifiable and can be acted on preemptively; an **uncertainty** cannot. **Risk = Probability × Impact.** Opportunities are the positive mirror.\n- Four stages: **identify → analyze → mitigate → control & document** (build the knowledge base).\n- **Qualitative**: plot risks on a **probability--impact matrix**; red-zone risks get a written plan *before* the event.\n- **Quantitative**: **EMV** = probability × impact; **decision trees** compare choices with chance events; Monte Carlo for whole-network risk.\n- Responses: **accept, minimize, share, transfer, reserve.** Pick per risk; ring-fence reserve against the biggest ones.\n- **Task contingency** is the PM's; **managerial contingency** is management's, for the truly unforeseeable.\n- **FMEA** systematically surfaces technical failure modes, causes, and effects.\n\n## Practice Problems\n\n<details>\n<summary>Problem 1: The road-trip risk register (from the course exercise)</summary>\n\nSix friends borrow an older car and drive to an unfamiliar beach. The weather\nforecast is mixed with a chance of rain and high winds; one friend is a very\npicky eater; the owner plans to replace the car soon due to problems; there is a\nfireworks show and all-day music at a crowded venue. List the risks, classify\neach, and give a mitigation strategy.\n\n**Model answer (partial).**\n\n| Risk | Class | Strategy |\n|---|---|---|\n| Get lost / arrive late | Schedule | *Minimize* --- offline map, leave early |\n| Car breaks down | Technology / Resources | *Minimize* (check oil, tires) + *transfer* (roadside assistance) |\n| Rain / high winds spoil the day | Weather | *Accept* + *minimize* (pack a tarp, check the radar) |\n| Picky eater has nothing to eat | Resources | *Minimize* --- bring a known-safe option |\n| No parking at a crowded venue | Resources | *Minimize* --- arrive before the crowd |\n| Injury in the crowd / fireworks | Environmental / Safety | *Minimize* --- agree a meeting point, stay together |\n\n</details>\n\n<details>\n<summary>Problem 2: EMV of competing suppliers</summary>\n\nSupplier X: \\$140 000, 15 % chance of a 3-week slip costing \\$45 000.\nSupplier Y: \\$128 000, 35 % chance of a 3-week slip costing \\$45 000.\nOn expected cost alone, which is cheaper?\n\n**Solution.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- 140000 + 0.15 * 45000\nY <- 128000 + 0.35 * 45000\ncat(sprintf(\"Supplier X expected cost: $%s\\n\", format(X, big.mark = \" \")))\ncat(sprintf(\"Supplier Y expected cost: $%s\\n\", format(Y, big.mark = \" \")))\ncat(sprintf(\"Cheaper on EMV: Supplier %s\\n\", ifelse(X < Y, \"X\", \"Y\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSupplier X expected cost: $146 750\nSupplier Y expected cost: $143 750\nCheaper on EMV: Supplier Y\n```\n\n\n:::\n:::\n\n\nX: \\$146 750. Y: \\$143 750. Y is cheaper on expected cost --- but note X's risk is\n*less likely*, which may matter more than the \\$3 000 if a slip would blow the\nholiday launch window. EMV informs the decision; it does not make it.\n\n</details>\n\n<details>\n<summary>Problem 3 (discussion): red-zone risk with no cheap mitigation</summary>\n\nThe \"carbon-fibre plant disruption\" risk sits in the red zone, but the supplier\nis the only qualified source and re-qualifying another would take four months you\ndo not have. What are your options?\n\n**Discussion points.** You cannot *minimize* the probability much, so work the\n**impact**: build a larger **contingency reserve** (time and money) against it;\n**transfer** part of it via contract terms (penalty clauses, guaranteed\nallocation); **share** it by co-investing in the supplier's modernization for\npriority supply; carry **safety stock** of the critical carbon-fibre parts; and\ndesign a **fallback** (an aluminium body variant) that could be substituted if\nthe supply fails, accepting a heavier product rather than a missed launch.\n\n</details>\n\n## Further Resources\n\n\n<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;\">\n  <iframe\n    style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\"\n    src=\"https://www.youtube.com/embed/vmkdHT9VmZg\"\n    title=\"Decision Tree Analysis for Calculating EMV (PMC Lounge)\"\n    frameborder=\"0\"\n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n    referrerpolicy=\"strict-origin-when-cross-origin\"\n    allowfullscreen>\n  </iframe>\n</div>\n\n<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;\">\n  <iframe\n    style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\"\n    src=\"https://www.youtube.com/embed/uC2XBGpIcAs\"\n    title=\"Decision Tree and Expected Monetary Value (Cornelius Fichtner)\"\n    frameborder=\"0\"\n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n    referrerpolicy=\"strict-origin-when-cross-origin\"\n    allowfullscreen>\n  </iframe>\n</div>\n",
    "supporting": [
      "07-Risk-Management_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}