{
  "hash": "c030192feb8a34699d912106162f25f2",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Cost Estimation and Budgeting\n\n\n\n## Learning Objectives\n\nBy the end of this chapter you will be able to:\n\n1. **List** the common sources of project cost and **classify** any cost against the four cost dichotomies (direct/indirect, fixed/variable, normal/expedited, recurring/non-recurring).\n2. **Calculate** direct labour cost from a rate and hours, and **apply** an indirect-cost percentage.\n3. **Select** an estimating method (ballpark, parametric, feasibility, definitive) appropriate to the project stage, and **state** its expected accuracy.\n4. **Explain** how planning horizon, duration, people, structure, padding, and organizational culture affect estimate quality.\n5. **Compare** top-down and bottom-up budgeting and **build** a bottom-up budget from a work breakdown structure using **activity-based costing**.\n6. **Construct** a time-phased budget and **plot** the cumulative cost baseline (the S-curve).\n7. **Size** a contingency reserve and **distinguish** it from a management reserve.\n\n<details>\n<summary>Before we begin: you have been asked for \"a number\" before you have any details</summary>\n\nA stakeholder corners you: *\"Ballpark it --- what will this project cost?\"* You\nhave a one-page concept and nothing else. What do you say, and how do you say it\nso the number does not follow you around for the next six months as a\ncommitment? Hold that thought.\n\n</details>\n\n## Introduction: the number that decides whether the project happens\n\nBack to the running project. Your company must present a budget to **Senior\nManagement before the Scope and Charter are approved**. The project brief hands\nyou rough ranges to work from:\n\n| Item | Range |\n|---|---|\n| Project Manager (salary) | \\$60 000 -- \\$80 000 |\n| Team members (salary, each) | \\$30 000 -- \\$45 000 |\n| Sundry / overhead (per hour) | \\$8.00 -- \\$15.00 |\n| Motor / controller | \\$100 000 -- \\$175 000 |\n| Carbon fibre | \\$120 000 -- \\$200 000 |\n| Aluminium | \\$50 000 -- \\$115 000 |\n| Tooling | \\$100 000 -- \\$180 000 |\n| Testing | \\$25 000 -- \\$100 000 |\n| Government approval (CSA, CE, MTO) | \\$2 000 -- \\$10 000 |\n| Packaging / shipping | \\$5 000 -- \\$25 000 |\n\n: Selected budget ranges from the RC-vehicle project brief\n\n**Cost estimation is the first step in building a budget, and the budget\ndetermines whether the project is feasible at all.** Two principles run through\neverything below:\n\n1. The more clearly you define each cost element up front, the fewer budgeting errors you make.\n2. The more accurate your initial estimate, the more your budget reflects reality --- and the less likely a painful overrun later.\n\n::: {.callout-note}\n**Industry snapshot.** A defense contractor bidding a **firm-fixed-price**\ncontract must submit a *definitive* estimate (±5 %): if the real cost comes in\nhigher, the contractor eats the difference. A food company scoping a new\nretort line at the concept stage lives with a *ballpark* (±30 %) and revises as\nquotes arrive. Same tools, very different tolerance for error --- driven by where\nin the project you are standing.\n:::\n\n\n**The ABCs of Project Cost Management (Adriana Girdler):** [https://www.youtube.com/watch?v=iEndSB5IgQM](https://www.youtube.com/watch?v=iEndSB5IgQM)\n\n## Where project cost comes from\n\nCost management starts in the **planning phase**, when you identify the project's\nhuman and material resources and lay out a **time-phased budget** that reflects\nwhen each will be used. The common sources of cost:\n\n- **Labour** --- the project team and anyone charging time to the project.\n- **Materials** --- everything consumed to build the deliverable.\n- **Subcontractors** --- external vendors, *and* internal support departments (test lab, drafting) that cross-charge.\n- **Equipment and facilities** --- purchased, leased, or allocated.\n- **Travel.**\n- **Shipping** --- inbound and outbound, normal and expedited.\n\n## The eight cost types\n\nEvery cost gets sorted into **one or more** of eight categories, arranged as\nfour either/or pairs. A single cost usually carries **two or three** labels at\nonce.\n\n\n::: {#tbl-cost-types-09 .cell}\n\n```{.r .cell-code}\ncost_types <- data.frame(\n  Dichotomy = c(\"Direct vs. Indirect\", \"\", \"Fixed vs. Variable\", \"\",\n                \"Normal vs. Expedited\", \"\", \"Recurring vs. Non-recurring\", \"\"),\n  Type = c(\"Direct\", \"Indirect\", \"Fixed\", \"Variable\",\n           \"Normal\", \"Expedited\", \"Recurring\", \"Non-recurring\"),\n  Meaning = c(\n    \"Clearly generated by the project (project labour, project materials, POs).\",\n    \"Overhead: rent, property tax, benefits, utilities, depreciation, admin. Often applied as 20--50 % of direct cost.\",\n    \"Does not change with usage (a 6-month equipment lease at a flat fee).\",\n    \"Proportional to usage (machine-hour charges, fuel, mileage).\",\n    \"Incurred during normal operation and working hours; includes overtime that was already scheduled.\",\n    \"Unplanned cost to go faster: rush freight, extra hires, premium to a supplier for priority.\",\n    \"Happens again through the project life: utilities, logistics, ongoing labour, monthly maintenance.\",\n    \"One-time, usually at the start or end: training, prototype tooling, initial market analysis.\"\n  )\n)\nknitr::kable(cost_types, align = c(\"l\", \"l\", \"l\"),\n             caption = \"The four cost dichotomies (eight types).\") |>\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n                            full_width = FALSE) |>\n  kableExtra::column_spec(2, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{l>{}ll}\n\\caption{\\label{tab:tbl-cost-types-09}The four cost dichotomies (eight types).}\\\\\n\\toprule\nDichotomy & Type & Meaning\\\\\n\\midrule\nDirect vs. Indirect & \\textbf{Direct} & Clearly generated by the project (project labour, project materials, POs).\\\\\n & \\textbf{Indirect} & Overhead: rent, property tax, benefits, utilities, depreciation, admin. Often applied as 20--50 \\% of direct cost.\\\\\nFixed vs. Variable & \\textbf{Fixed} & Does not change with usage (a 6-month equipment lease at a flat fee).\\\\\n & \\textbf{Variable} & Proportional to usage (machine-hour charges, fuel, mileage).\\\\\nNormal vs. Expedited & \\textbf{Normal} & Incurred during normal operation and working hours; includes overtime that was already scheduled.\\\\\n\\addlinespace\n & \\textbf{Expedited} & Unplanned cost to go faster: rush freight, extra hires, premium to a supplier for priority.\\\\\nRecurring vs. Non-recurring & \\textbf{Recurring} & Happens again through the project life: utilities, logistics, ongoing labour, monthly maintenance.\\\\\n & \\textbf{Non-recurring} & One-time, usually at the start or end: training, prototype tooling, initial market analysis.\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Direct labour cost\n\nThe core calculation is simple:\n\n$$\\text{Total Direct Labour Cost} = \\text{Direct Labour Rate} \\times \\text{Hours Spent}$$\n\nIndirect cost is harder to pin to a task, so many organizations apply it as a\n**percentage of direct cost**:\n\n$$\\text{Indirect Cost} = \\text{Indirect Rate} \\times \\text{Direct Cost}, \\qquad \\text{Indirect Rate} \\approx 20\\%\\text{--}50\\%$$\n\n### Worked Example 1: fully-burdened cost of a work package\n\nThe \"Design body & frame\" work package needs **1 mechanical designer for\n220 h** at \\$46/h and **1 junior engineer for 120 h** at \\$32/h. Direct\nmaterials for prototypes are \\$4 500. The company applies indirect cost at\n**35 %** of direct cost.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesigner_hours <- 220; designer_rate <- 46\njunior_hours   <- 120; junior_rate   <- 32\ndirect_materials <- 4500\nindirect_rate <- 0.35\n\ndirect_labour <- designer_hours * designer_rate + junior_hours * junior_rate\ndirect_cost   <- direct_labour + direct_materials\nindirect_cost <- indirect_rate * direct_cost\ntotal_cost    <- direct_cost + indirect_cost\n\ncat(\"Direct labour  :\", sprintf(\"$%s\", format(direct_labour, big.mark = \" \")), \"\\n\")\ncat(\"Direct materials:\", sprintf(\"$%s\", format(direct_materials, big.mark = \" \")), \"\\n\")\ncat(\"Direct cost    :\", sprintf(\"$%s\", format(direct_cost, big.mark = \" \")), \"\\n\")\ncat(\"Indirect (35%) :\", sprintf(\"$%s\", format(indirect_cost, big.mark = \" \")), \"\\n\")\ncat(\"-----\\n\")\ncat(\"Fully-burdened work-package cost:\",\n    sprintf(\"$%s\", format(round(total_cost), big.mark = \" \")), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDirect labour  : $13 960 \nDirect materials: $4 500 \nDirect cost    : $18 460 \nIndirect (35%) : $6 461 \n-----\nFully-burdened work-package cost: $24 921 \n```\n\n\n:::\n:::\n\n\n<details>\n<summary>Practice: classify the cost (from the MGMT-3105 budgeting case study)</summary>\n\nFor each item, give **up to three** labels from: A Direct, B Indirect, C Fixed,\nD Variable, E Recurring, F Non-recurring, G Normal, H Expedited.\n\n| # | Cost item | Answer |\n|---|---|---|\n| 1 | Technician's hourly wages for project assembly | A Direct, D Variable, G Normal |\n| 2 | Office rent for company headquarters | B Indirect, C Fixed, E Recurring |\n| 3 | One-time purchase of specialized testing software | A Direct, F Non-recurring |\n| 4 | Electricity used by production equipment | D Variable, E Recurring, B Indirect |\n| 6 | Hiring extra workers to meet a tight deadline | H Expedited, A Direct |\n| 9 | Rush shipment of components to meet schedule | H Expedited, A Direct |\n| 12 | Cost of the project manager's salary | C Fixed, E Recurring, A Direct |\n| 17 | Routine monthly maintenance of equipment | F ... *(trick: this is E Recurring, B Indirect)* |\n| 23 | Equipment lease for six months (flat fee) | B Indirect, C Fixed, E Recurring |\n| 40 | One-time cost for prototype tooling | A Direct, F Non-recurring, C Fixed |\n\nThe pattern: **anything charged straight to the project is Direct; overhead is\nIndirect; anything you pay to go faster is Expedited; anything paid once is\nNon-recurring.** Most items are genuinely two or three of these at once.\n\n</details>\n\n### The dichotomies on the running project\n\n- **Fixed vs. variable.** The 6-month lease on the CMM is **fixed** --- the fee is the same whether you measure 50 parts or 5 000. The machine-hour charge on the rented moulding press is **variable**. Leasing an expensive machine is a real PM judgement call: will the usage justify the flat fee?\n- **Normal vs. expedited.** Air-freighting circuit boards from the supplier to recover a slipped date is **expedited** and **direct**. The overtime you *planned* into the schedule from day one is still **normal**.\n- **Recurring vs. non-recurring.** Prototype tooling and the initial market analysis are **non-recurring**. Utilities, logistics, and the team's salaries are **recurring** --- and it matters which is which the moment you build a time-phased budget.\n\n## Estimating methods and their accuracy\n\nThe method you can use depends on how much you know, which depends on how far\ninto the project you are.\n\n\n::: {#tbl-estimate-methods-09 .cell}\n\n```{.r .cell-code}\nmethods <- data.frame(\n  Method = c(\"Ballpark / order-of-magnitude\", \"Comparative / parametric\",\n             \"Feasibility\", \"Definitive\"),\n  `When` = c(\n    \"Very early; scarce time/resources; deciding whether to even bid.\",\n    \"A genuinely similar past project exists, with reliable archived actuals.\",\n    \"Scope is clear and first supplier quotes are back (common in construction).\",\n    \"Most design is complete; major POs can be written; detail is known.\"\n  ),\n  Accuracy = c(\"+/- 30 %\", \"+/- 15 %\", \"+/- 10 %\", \"+/- 5 %\"),\n  check.names = FALSE\n)\nknitr::kable(methods, align = c(\"l\", \"l\", \"c\"),\n             caption = \"Estimating methods by project stage and typical accuracy.\") |>\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n                            full_width = FALSE) |>\n  kableExtra::column_spec(3, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{ll>{}c}\n\\caption{\\label{tab:tbl-estimate-methods-09}Estimating methods by project stage and typical accuracy.}\\\\\n\\toprule\nMethod & When & Accuracy\\\\\n\\midrule\nBallpark / order-of-magnitude & Very early; scarce time/resources; deciding whether to even bid. & \\textbf{+/- 30 \\%}\\\\\nComparative / parametric & A genuinely similar past project exists, with reliable archived actuals. & \\textbf{+/- 15 \\%}\\\\\nFeasibility & Scope is clear and first supplier quotes are back (common in construction). & \\textbf{+/- 10 \\%}\\\\\nDefinitive & Most design is complete; major POs can be written; detail is known. & \\textbf{+/- 5 \\%}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\nThis is the **cone of uncertainty**: the possible range around an estimate is\nwidest at the concept stage and narrows as the project is defined.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncone <- data.frame(\n  stage = factor(c(\"Ballpark\", \"Parametric\", \"Feasibility\", \"Definitive\"),\n                 levels = c(\"Ballpark\", \"Parametric\", \"Feasibility\", \"Definitive\")),\n  x = 1:4,\n  err = c(0.30, 0.15, 0.10, 0.05)\n)\npoint_estimate <- 1.0  # $M\n\nggplot(cone, aes(x = x)) +\n  geom_ribbon(aes(ymin = point_estimate * (1 - err),\n                  ymax = point_estimate * (1 + err)),\n              fill = \"#5DADE2\", alpha = 0.35) +\n  geom_line(aes(y = point_estimate * (1 + err)), linewidth = 1, color = \"#2E86C1\") +\n  geom_line(aes(y = point_estimate * (1 - err)), linewidth = 1, color = \"#2E86C1\") +\n  annotate(\"segment\", x = 0.7, xend = 4.3, y = point_estimate, yend = point_estimate,\n           linetype = \"dashed\", color = \"grey30\") +\n  annotate(\"text\", x = 4.3, y = point_estimate, label = \"point estimate  $1.0M\",\n           hjust = 1, vjust = -0.7, size = 3.3 * diagram_text_scale) +\n  geom_point(aes(y = point_estimate * (1 + err)), size = 2.5, color = \"#1B4F72\") +\n  geom_point(aes(y = point_estimate * (1 - err)), size = 2.5, color = \"#1B4F72\") +\n  geom_text(aes(y = point_estimate * (1 + err),\n                label = paste0(\"+\", scales::percent(err, accuracy = 1))),\n            vjust = -0.8, size = 3.2 * diagram_text_scale) +\n  geom_text(aes(y = point_estimate * (1 - err),\n                label = paste0(\"-\", scales::percent(err, accuracy = 1))),\n            vjust = 1.6, size = 3.2 * diagram_text_scale) +\n  scale_x_continuous(breaks = 1:4, labels = levels(cone$stage)) +\n  scale_y_continuous(labels = scales::dollar_format(suffix = \"M\", big.mark = \" \")) +\n  labs(title = \"The cone of uncertainty\", x = NULL, y = \"Estimated project cost\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 14 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 10 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![The cone of uncertainty. Early estimates can be off by +/- 30 %; the range narrows to +/- 5 % only once most design decisions are locked. The same $1.0M point estimate means very different things at each stage.](09-Cost-Estimation-and-Budgeting_files/figure-pdf/fig-cone-of-uncertainty-09-1.pdf){#fig-cone-of-uncertainty-09 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n### Try it yourself: parametric estimate and the accuracy band\n\nA **parametric** estimate uses a cost-estimating relationship (CER) from history\n--- for example, \"past RC-vehicle projects cost about \\$14.50 per assembled part\nplus \\$85 000 of fixed project cost.\" The live cell builds the estimate and\nshows the band each method would put around it.\n\n```{webr-r}\n#| label: parametric-estimate-09\nunits             <- 120000\ncost_per_unit_CER <- 14.50      # $/unit, from archived projects\nfixed_project_cost<- 85000      # $, setup / PM / approvals\n\npoint_estimate <- units * cost_per_unit_CER + fixed_project_cost\n\nbands <- data.frame(\n  method   = c(\"Ballpark\", \"Parametric\", \"Feasibility\", \"Definitive\"),\n  accuracy = c(0.30,        0.15,         0.10,          0.05)\n)\nbands$low  <- round(point_estimate * (1 - bands$accuracy))\nbands$high <- round(point_estimate * (1 + bands$accuracy))\n\ncat(sprintf(\"Parametric point estimate: $%s\\n\\n\",\n            format(round(point_estimate), big.mark = \" \")))\nfor (i in seq_len(nrow(bands))) {\n  cat(sprintf(\"%-11s (+/- %2.0f%%):  $%s  ...  $%s\\n\",\n              bands$method[i], bands$accuracy[i] * 100,\n              format(bands$low[i],  big.mark = \" \"),\n              format(bands$high[i], big.mark = \" \")))\n}\n```\n\n<details>\n<summary>Why quote a range at all --- why not just give \"the number\"?</summary>\n\nBecause a single number reads as a **commitment**. If you say \"\\$1.8M\" at the\nconcept stage and the definitive estimate later lands at \\$2.0M, you have\n\"overrun by \\$200k\" --- even though \\$2.0M was always inside the ±30 % ballpark\nband. Quoting \"\\$1.3M--\\$2.3M, ballpark\" sets the expectation honestly and buys\nyou room to refine. A clear distinction between an **estimate** and a\n**commitment** is one of the most important things a PM can establish early.\n\n</details>\n\n## What makes estimates good or bad\n\n| Factor | Effect on estimate quality |\n|---|---|\n| **Planning horizon** | Estimates of near-term work are close to 100 % accurate; accuracy falls the further out the task sits. |\n| **Project duration** | Long projects and new technology add uncertainty, especially if the scope statement is weak. |\n| **People** | The closer the estimator's experience matches the work, the better. Teams that have worked together before form faster. Staff turnover hurts. |\n| **Structure** | Dedicated teams deliver faster but tie up people full-time. Matrix organizations are more cost-efficient but slower. |\n| **Padding** | Estimators add a safety margin. If *everyone* pads a little, the project total is badly overstated and stops reflecting reality. |\n| **Organizational culture** | Some cultures reward padding; others prize accuracy. The consequences an estimator faces for a miss shape the number they give. |\n| **Other** | Equipment downtime, sickness, vacation, holidays, legal limits, and project priority all leak into the estimate. |\n\n### The cost of padding\n\nPadding feels prudent per task. Watch what it does across a whole project.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2025)\nn_tasks <- 40\ntrue_mean <- 40           # hours, honest most-likely per task\n# Honest estimates vary around the truth; padded estimates add 15% on top.\nhonest  <- rnorm(n_tasks, true_mean, 6)\npadded  <- honest * 1.15\n\ndf <- data.frame(\n  task = 1:n_tasks,\n  honest_cum = cumsum(honest),\n  padded_cum = cumsum(padded)\n)\n\nggplot(df, aes(x = task)) +\n  geom_line(aes(y = honest_cum, color = \"Honest estimate\"), linewidth = 1.1) +\n  geom_line(aes(y = padded_cum, color = \"Every task padded 15%\"), linewidth = 1.1) +\n  annotate(\"text\", x = n_tasks, y = df$padded_cum[n_tasks],\n           label = paste0(\"+\", round(100 * (df$padded_cum[n_tasks] /\n                          df$honest_cum[n_tasks] - 1)), \"% on the total\"),\n           hjust = 1, vjust = -0.6, size = 3.4 * diagram_text_scale) +\n  scale_color_manual(values = c(\"Honest estimate\" = \"#27AE60\",\n                                \"Every task padded 15%\" = \"#C0392B\")) +\n  labs(title = \"Per-task padding compounds into a meaningless total\",\n       x = \"Cumulative task count\", y = \"Cumulative estimated hours\",\n       color = NULL) +\n  theme_minimal() +\n  theme(\n    legend.position = \"top\",\n    plot.title = element_text(size = 14 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 10 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![A 15 % 'just to be safe' pad added to every one of 40 tasks does not add 15 % to the project --- it adds 15 % to the mean, but the padded total sits far above any realistic outcome because the pads do not all get used.](09-Cost-Estimation-and-Budgeting_files/figure-pdf/fig-padding-compounding-09-1.pdf){#fig-padding-compounding-09 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nThe fix is not \"ban all safety margin\" --- it is to **remove padding from the\nwork packages** and hold a single, visible **contingency reserve** at the\nproject level (covered below).\n\n### Guidelines for estimating (cost and time)\n\n- **Responsibility:** the person who will do the task makes the estimate (except for highly specialised work). It uses their experience and builds their buy-in.\n- **Use several estimators:** independent estimates from knowledgeable people, reconciled, remove the extremes.\n- **Assume normal conditions:** normal hours, normal resource levels --- and write the assumptions down.\n- **Define the time units** and the estimating base.\n- **Estimate each task independently;** be careful with chains of dependent tasks, and keep one estimator per task.\n- **Keep contingencies out of the work packages.** Contingency is a separate, managed fund.\n\n## Budgeting: top-down and bottom-up\n\nThe budget and the schedule are built **in tandem** --- the budget decides\nwhether the schedule's milestones are reachable.\n\n\n::: {#tbl-topdown-bottomup-09 .cell}\n\n```{.r .cell-code}\napproaches <- data.frame(\n  Aspect = c(\"How it starts\", \"Advantages\", \"Disadvantages\"),\n  `Top-down` = c(\n    \"Senior management sets the overall budget and major work-package figures from experience; the numbers are pushed down the hierarchy and refined.\",\n    \"Management aggregate estimates are often quite accurate; imposes budget discipline and cost control.\",\n    \"Creates friction: lower levels must fit management's fixed total. Turns into a zero-sum game between functions.\"\n  ),\n  `Bottom-up` = c(\n    \"Start from the WBS; apply direct and indirect cost to each activity; sum up to work package, deliverable, then project.\",\n    \"Forces detailed planning; improves PM--functional-manager communication; gives management a clear basis for prioritizing scarce resources.\",\n    \"Reduces management's control to oversight rather than initiation; can misalign project goals with company goals; fine-tuning is time-consuming.\"\n  ),\n  check.names = FALSE\n)\nknitr::kable(approaches, align = c(\"l\", \"l\", \"l\"),\n             caption = \"Top-down vs. bottom-up budgeting.\") |>\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n                            full_width = FALSE) |>\n  kableExtra::column_spec(1, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:tbl-topdown-bottomup-09}Top-down vs. bottom-up budgeting.}\\\\\n\\toprule\nAspect & Top-down & Bottom-up\\\\\n\\midrule\n\\textbf{How it starts} & Senior management sets the overall budget and major work-package figures from experience; the numbers are pushed down the hierarchy and refined. & Start from the WBS; apply direct and indirect cost to each activity; sum up to work package, deliverable, then project.\\\\\n\\textbf{Advantages} & Management aggregate estimates are often quite accurate; imposes budget discipline and cost control. & Forces detailed planning; improves PM--functional-manager communication; gives management a clear basis for prioritizing scarce resources.\\\\\n\\textbf{Disadvantages} & Creates friction: lower levels must fit management's fixed total. Turns into a zero-sum game between functions. & Reduces management's control to oversight rather than initiation; can misalign project goals with company goals; fine-tuning is time-consuming.\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n## Activity-based costing (ABC)\n\nABC treats a project as a series of **activities**, each of which **consumes\nresources**. Cost the activities and you have costed the project. Four steps:\n\n1. Identify the activities that consume resources and assign costs to them.\n2. Identify the **cost drivers** for each activity (personnel, materials, machine time...).\n3. Compute a **cost rate per driver unit** (e.g. labour \\$/hour).\n4. **Assign cost** = rate × units the project uses. *(Example: an engineer at \\$60/h working 80 h = \\$4 800.)*\n\n### A preliminary ABC budget\n\nSplitting each activity into its **direct** and **overhead** components:\n\n\n::: {#tbl-abc-budget-09 .cell}\n\n```{.r .cell-code}\nabc <- data.frame(\n  Activity   = c(\"Survey\", \"Design\", \"Clear site\", \"Foundation\", \"Framing\", \"Plumb & wire\"),\n  Direct     = c(3500, 7000, 3500, 6750, 8000, 3750),\n  Overhead   = c(500, 1000, 500, 750, 2000, 1250)\n)\nabc$Total <- abc$Direct + abc$Overhead\nabc <- rbind(abc, data.frame(Activity = \"TOTAL\",\n                             Direct = sum(abc$Direct),\n                             Overhead = sum(abc$Overhead),\n                             Total = sum(abc$Total)))\n\nknitr::kable(abc, align = c(\"l\", \"r\", \"r\", \"r\"),\n             format.args = list(big.mark = \" \"),\n             caption = \"Preliminary ABC budget: direct vs. overhead by activity.\") |>\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n                            full_width = FALSE) |>\n  kableExtra::row_spec(nrow(abc), bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lrrr}\n\\caption{\\label{tab:tbl-abc-budget-09}Preliminary ABC budget: direct vs. overhead by activity.}\\\\\n\\toprule\nActivity & Direct & Overhead & Total\\\\\n\\midrule\nSurvey & 3 500 & 500 & 4 000\\\\\nDesign & 7 000 & 1 000 & 8 000\\\\\nClear site & 3 500 & 500 & 4 000\\\\\nFoundation & 6 750 & 750 & 7 500\\\\\nFraming & 8 000 & 2 000 & 10 000\\\\\n\\addlinespace\nPlumb \\& wire & 3 750 & 1 250 & 5 000\\\\\n\\textbf{TOTAL} & \\textbf{32 500} & \\textbf{6 000} & \\textbf{38 500}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Try it yourself: cost an activity, then a variance\n\nThe live cell costs a single activity from its drivers, then compares planned\nvs. actual to get the **variance**. Change the rates, hours, or actuals.\n\n```{webr-r}\n#| label: abc-activity-variance-09\n# --- Step 3 & 4: cost the \"Assemble & test prototype\" activity from drivers ---\nlabour_rate   <- 38;  labour_hours   <- 160\nmachine_rate  <- 22;  machine_hours  <- 45\nmaterials     <- 2600\noverhead_rate <- 0.30            # 30% of direct\n\ndirect   <- labour_rate * labour_hours + machine_rate * machine_hours + materials\noverhead <- overhead_rate * direct\nplanned  <- direct + overhead\n\ncat(sprintf(\"Direct   : $%s\\n\", format(round(direct),   big.mark = \" \")))\ncat(sprintf(\"Overhead : $%s\\n\", format(round(overhead), big.mark = \" \")))\ncat(sprintf(\"Planned activity cost: $%s\\n\\n\", format(round(planned), big.mark = \" \")))\n\n# --- Variance: what actually happened ---\nactual <- 11800\nvariance <- planned - actual          # positive = under budget (favourable)\npct <- 100 * variance / planned\n\nverdict <- if (variance >= 0) \"UNDER budget (favourable)\" else \"OVER budget (unfavourable)\"\ncat(sprintf(\"Actual   : $%s\\n\", format(actual, big.mark = \" \")))\ncat(sprintf(\"Variance : $%s  (%.1f%%)  -> %s\\n\",\n            format(round(variance), big.mark = \" \"), pct, verdict))\n```\n\n::: {.callout-warning}\n**Common mistake.** Contingency is **not** built into an ABC budget. ABC costs\nthe activities as they are planned to run; the contingency reserve is added\n*afterward*, on top of the total.\n:::\n\n## The time-phased budget and the S-curve\n\nA **time-phased budget** spreads each activity's cost across the calendar\nperiods when it will actually be spent. Summing down the columns gives\n**monthly planned spend**; the running total is the **cumulative cost\nbaseline** --- the S-curve you will track the project against in\n[Chapter 12](12-Project-Control-Systems.qmd).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nphased <- data.frame(\n  month = factor(c(\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\"),\n                 levels = c(\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\")),\n  Survey       = c(4000, 3000,     0,     0,    0),\n  Design       = c(   0, 5000,  8000,     0,    0),\n  ClearSite    = c(   0, 1000,  4000,  2000,    0),\n  Foundation   = c(   0,    0,  3000,  4000,    0),\n  Framing      = c(   0,    0,     0,  3000, 4000),\n  PlumbWire    = c(   0,    0,     0,     0, 2000)\n)\nphased$monthly <- rowSums(phased[, -1])\nphased$cumulative <- cumsum(phased$monthly)\n\nscale_factor <- max(phased$cumulative) / max(phased$monthly)\n\nggplot(phased, aes(x = month)) +\n  geom_col(aes(y = monthly), fill = \"#5DADE2\", width = 0.6) +\n  geom_line(aes(y = cumulative / scale_factor, group = 1),\n            color = \"#C0392B\", linewidth = 1.2) +\n  geom_point(aes(y = cumulative / scale_factor), color = \"#C0392B\", size = 3) +\n  geom_text(aes(y = cumulative / scale_factor,\n                label = scales::dollar(cumulative, big.mark = \" \")),\n            vjust = -1, size = 3.2 * diagram_text_scale, color = \"#C0392B\") +\n  scale_y_continuous(\n    name = \"Planned spend this month\",\n    labels = scales::dollar_format(big.mark = \" \"),\n    sec.axis = sec_axis(~ . * scale_factor, name = \"Cumulative baseline (S-curve)\",\n                        labels = scales::dollar_format(big.mark = \" \"))\n  ) +\n  labs(title = \"Time-phased budget and cumulative cost baseline\", x = NULL) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 14 * diagram_text_scale, face = \"bold\"),\n    axis.title = element_text(size = 11 * diagram_text_scale),\n    axis.text = element_text(size = 10 * diagram_text_scale)\n  )\n```\n\n::: {.cell-output-display}\n![Time-phased budget for a six-activity project. Bars are planned spend per month; the line is the cumulative baseline (the S-curve). Spend is slow at first, steepest mid-project, and tapers at the end.](09-Cost-Estimation-and-Budgeting_files/figure-pdf/fig-s-curve-09-1.pdf){#fig-s-curve-09 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nMatching the cost baseline to the schedule baseline is what lets you set\n**milestones for both schedule and budget** and later tell whether a project\nthat has spent 60 % of its money is 60 %, 40 %, or 80 % done.\n\n## Contingency reserves\n\nA **budget contingency** is extra money set aside to cover the uncertainty that\nevery estimate carries --- because even the best budget is only an estimate and\nsomething unforeseen always happens. Key points:\n\n- Added **after all costs are identified**, as a cushion on top of the calculated total (commonly **10--15 %**; the MGMT-3105 Costs Chart uses **15 %**).\n- **Not** included in an ABC budget --- it sits on top.\n- The **PM controls a project contingency fund**; separately, **top management holds a management reserve** for genuinely unknown-unknown events.\n\nWhy stakeholders push back: the percentage can look arbitrary, or feel like\nbeing asked to pay for the vendor's poor cost control. Decide early --- and write\ninto the scope statement --- whether contingency applies across **all** tasks or\nis held for the tasks **critical** to project success.\n\n\n::: {#tbl-reserve-vs-reserve-09 .cell}\n\n```{.r .cell-code}\nreserves <- data.frame(\n  Feature = c(\"Covers\", \"Owned by\", \"Part of the cost baseline?\", \"Typical size\"),\n  `Contingency reserve` = c(\n    \"Identified risks / \\\"known-unknowns\\\" (small scope adjustments, iteration, Murphy's Law).\",\n    \"Project manager.\",\n    \"Yes --- inside the baseline.\",\n    \"10--15 % of estimated cost (project-dependent).\"\n  ),\n  `Management reserve` = c(\n    \"Unidentified risks / \\\"unknown-unknowns.\\\"\",\n    \"Senior management / sponsor.\",\n    \"No --- outside the baseline; released by management.\",\n    \"Set by organizational policy.\"\n  ),\n  check.names = FALSE\n)\nknitr::kable(reserves, align = c(\"l\", \"l\", \"l\"),\n             caption = \"Contingency reserve vs. management reserve.\") |>\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n                            full_width = FALSE) |>\n  kableExtra::column_spec(1, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:tbl-reserve-vs-reserve-09}Contingency reserve vs. management reserve.}\\\\\n\\toprule\nFeature & Contingency reserve & Management reserve\\\\\n\\midrule\n\\textbf{Covers} & Identified risks / \"known-unknowns\" (small scope adjustments, iteration, Murphy's Law). & Unidentified risks / \"unknown-unknowns.\"\\\\\n\\textbf{Owned by} & Project manager. & Senior management / sponsor.\\\\\n\\textbf{Part of the cost baseline?} & Yes --- inside the baseline. & No --- outside the baseline; released by management.\\\\\n\\textbf{Typical size} & 10--15 \\% of estimated cost (project-dependent). & Set by organizational policy.\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Try it yourself: build the RC-vehicle project budget\n\nThe live cell builds a rough **bottom-up** budget from the project brief's\nranges (using a pick inside each range), rolls up labour and materials, and adds\na contingency. Change the picks or the contingency rate and watch the total ---\nthen check it against what Senior Management is likely to approve.\n\n```{webr-r}\n#| label: rc-project-budget-09\n# --- Labour (annualised salaries prorated to a 7-month project = 7/12) ---\nmonths <- 7\npm_salary        <- 72000\nn_team           <- 4\nteam_salary_each <- 38000\nsundry_per_hour  <- 11\nsundry_hours     <- 1800          # total support hours booked to the project\n\nlabour <- (pm_salary + n_team * team_salary_each) * months / 12 +\n          sundry_per_hour * sundry_hours\n\n# --- Materials (one pick inside each brief range) ---\nmaterials <- c(\n  chassis_casting   = 55000,\n  fasteners         = 9000,\n  motor_controller  = 140000,\n  carbon_fibre      = 0,          # not selected this time\n  aluminium         = 85000,\n  welding           = 25000,\n  circuit_boards    = 32000,\n  gov_approval      = 6000,\n  testing           = 60000,\n  tooling           = 150000,\n  safety_equipment  = 50000,\n  packaging_shipping= 15000\n)\nmaterial_total <- sum(materials)\n\nsubtotal      <- labour + material_total\ncontingency_r <- 0.15\ncontingency   <- contingency_r * subtotal\ngrand_total   <- subtotal + contingency\n\ncat(sprintf(\"Labour subtotal      : $%s\\n\", format(round(labour),        big.mark = \" \")))\ncat(sprintf(\"Material subtotal     : $%s\\n\", format(round(material_total),big.mark = \" \")))\ncat(sprintf(\"Subtotal             : $%s\\n\", format(round(subtotal),      big.mark = \" \")))\ncat(sprintf(\"Contingency (%.0f%%)     : $%s\\n\", contingency_r * 100,\n            format(round(contingency), big.mark = \" \")))\ncat(sprintf(\"--------\\nGRAND TOTAL          : $%s\\n\",\n            format(round(grand_total), big.mark = \" \")))\n```\n\n<details>\n<summary>How would top-down vs. bottom-up change this number?</summary>\n\nThe cell above is **bottom-up**: it sums the pieces and lets the total fall out.\nA **top-down** pass would start with a figure Senior Management is willing to\nfund --- say \"\\$650k, no more\" --- and force each line to fit. In practice you do\nboth: build bottom-up for defensibility, compare to the top-down ceiling, and\nnegotiate the gap before the Charter is signed. If bottom-up comes in well over\nthe ceiling, that is a **feasibility** finding, not a rounding problem.\n\n</details>\n\n## Key Takeaways\n\n- Cost management starts in **planning**. Sources: labour, materials, subcontractors, equipment/facilities, travel, shipping.\n- Every cost carries **two or three** of the eight labels: direct/indirect, fixed/variable, normal/expedited, recurring/non-recurring. **Direct labour cost = rate × hours**; indirect is often **20--50 % of direct**.\n- Estimating method follows project stage: **ballpark ±30 %, parametric ±15 %, feasibility ±10 %, definitive ±5 %** --- the **cone of uncertainty**. Always quote a **range**, and keep \"estimate\" separate from \"commitment.\"\n- Estimate quality is driven by planning horizon, duration, people, structure, culture, and **padding** --- which compounds into a meaningless total. Remove pads from work packages; hold one visible contingency.\n- **Top-down** imposes discipline but breeds friction; **bottom-up** (via **activity-based costing** on the WBS) forces real planning. ABC = identify activities → cost drivers → rate per unit → rate × units.\n- A **time-phased budget** produces the **cumulative cost baseline (S-curve)** you track against later.\n- **Contingency reserve** (10--15 %, PM-owned, inside the baseline, covers known-unknowns) is distinct from the **management reserve** (sponsor-owned, outside the baseline, covers unknown-unknowns). Contingency is added **after** ABC, never inside it.\n\n## Practice Problems\n\n<details>\n<summary>Problem 1: Fully-burdened labour and an indirect-rate swing</summary>\n\nA test campaign needs 2 technicians for 3 weeks (37.5 h/week each) at \\$34/h,\nplus \\$6 200 of consumables. Compute the fully-burdened cost at an indirect rate\nof 25 %, and again at 45 %. How much does the indirect-rate assumption alone\nmove the number?\n\n**Solution.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntechs <- 2; weeks <- 3; hrs_week <- 37.5; rate <- 34\nconsumables <- 6200\n\ndirect_labour <- techs * weeks * hrs_week * rate\ndirect_cost   <- direct_labour + consumables\n\nfor (ir in c(0.25, 0.45)) {\n  total <- direct_cost * (1 + ir)\n  cat(sprintf(\"Indirect %2.0f%%:  direct $%s  +  indirect $%s  =  $%s\\n\",\n              ir * 100,\n              format(direct_cost, big.mark = \" \"),\n              format(round(direct_cost * ir), big.mark = \" \"),\n              format(round(total), big.mark = \" \")))\n}\ncat(sprintf(\"\\nSwing from the indirect-rate assumption alone: $%s\\n\",\n            format(round(direct_cost * (0.45 - 0.25)), big.mark = \" \")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIndirect 25%:  direct $13 850  +  indirect $3 462  =  $17 312\nIndirect 45%:  direct $13 850  +  indirect $6 232  =  $20 082\n\nSwing from the indirect-rate assumption alone: $2 770\n```\n\n\n:::\n:::\n\n\nThe direct cost is fixed at \\$21 500, but the burdened total moves by \\$4 300 ---\n20 % of direct --- purely on the overhead assumption. Always state the indirect\nrate you used.\n\n</details>\n\n<details>\n<summary>Problem 2: Which estimating method, and what range?</summary>\n\nFor each situation, name the method and give the ± band around a \\$500 000 point\nestimate.\n\n(a) A retailer asks, in a hallway, roughly what a new product line will cost.\nYou have a concept sketch.\n(b) You have run three near-identical RC-vehicle launches in the last four years\nwith clean cost records.\n(c) All major POs are drafted and 90 % of the design is released for a\nfirm-fixed-price defense bid.\n\n**Solution.**\n\n- (a) **Ballpark**, ±30 % → \\$350 000 -- \\$650 000.\n- (b) **Comparative/parametric**, ±15 % → \\$425 000 -- \\$575 000.\n- (c) **Definitive**, ±5 % → \\$475 000 -- \\$525 000. (Anything looser is a bad idea on a fixed-price bid.)\n\n</details>\n\n<details>\n<summary>Problem 3: Variance analysis on the ABC budget</summary>\n\nUsing the preliminary ABC budget above (total planned \\$63 250), the project\nfinishes with these actuals: Survey \\$4 250, Design \\$8 000, Clear site \\$3 500,\nFoundation \\$8 500, Framing \\$11 250, Plumb & wire \\$5 150. Find the variance per\nactivity and overall, and flag the activities that need a post-mortem.\n\n**Solution.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplanned <- c(Survey = 4000, Design = 8000, `Clear site` = 4000,\n             Foundation = 7500, Framing = 10000, `Plumb & wire` = 5000)\nactual  <- c(4250, 8000, 3500, 8500, 11250, 5150)\n\nvariance <- planned - actual            # + = under budget\ntab <- data.frame(Activity = names(planned),\n                  Planned = as.integer(planned),\n                  Actual = as.integer(actual),\n                  Variance = as.integer(variance),\n                  Pct = round(100 * variance / planned, 1))\nprint(tab, row.names = FALSE)\n\ncat(sprintf(\"\\nTOTAL planned $%s  actual $%s  variance $%s (%.1f%%)\\n\",\n            format(sum(planned), big.mark = \" \"),\n            format(sum(actual),  big.mark = \" \"),\n            format(sum(variance), big.mark = \" \"),\n            100 * sum(variance) / sum(planned)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Activity Planned Actual Variance   Pct\n       Survey    4000   4250     -250  -6.2\n       Design    8000   8000        0   0.0\n   Clear site    4000   3500      500  12.5\n   Foundation    7500   8500    -1000 -13.3\n      Framing   10000  11250    -1250 -12.5\n Plumb & wire    5000   5150     -150  -3.0\n\nTOTAL planned $38 500  actual $40 650  variance $-2 150 (-5.6%)\n```\n\n\n:::\n:::\n\n\nDesign and (roughly) Survey held. **Foundation (-13 %)** and **Framing (-13 %)**\nblew through and drove the whole project \\$2 150 (3.4 %) over --- those two get\nthe post-mortem.\n\n</details>\n\n<details>\n<summary>Problem 4 (discussion): sizing contingency for the RC-vehicle project</summary>\n\nThe project brief flags several live risks: one candidate motor supplier is\nunproven, that supplier's staff are negotiating a first labour contract, the\ncarbon-fibre supplier is mid-restructuring after an acquisition, and a new\nassembly line would carry a learning curve. The subtotal budget is \\$620 000.\n\nWould you size the contingency at 10 %, 15 %, or 20 %? Would you spread it\nacross all tasks or ring-fence it for specific ones? Defend your answer.\n\n**Discussion points.** With that many concentrated, plausible risks, **10 % is\nlight**; 15 % is defensible and matches the course's Costs Chart; 20 % is\narguable if the unproven-supplier and new-line risks are both realised. A strong\nanswer **ring-fences** most of the reserve against the supplier and\nassembly-line line items (the tasks critical to success) rather than smearing it\nevenly, and states that split in the scope statement so stakeholders are not\nsurprised when it is drawn down.\n\n</details>\n\n## Further Resources\n\n- **Cost estimating techniques (analogous, parametric, bottom-up):** curated explainer videos below.\n- Preview of [Chapter 12 --- Project Control Systems](12-Project-Control-Systems.qmd): the S-curve you built here becomes the baseline for **earned value** analysis.\n\n\n**The Basics of Project Cost Management (ProjectManager):** [https://www.youtube.com/watch?v=EyPFi0YO32M](https://www.youtube.com/watch?v=EyPFi0YO32M)\n\n\n\n**Cost Estimates - Key Concepts in Project Management (David McLachlan):** [https://www.youtube.com/watch?v=hfn9VCAj4Dw](https://www.youtube.com/watch?v=hfn9VCAj4Dw)\n\n\n\n**How to Estimate Project Costs Accurately:** [https://www.youtube.com/watch?v=2IxoWVjsphc](https://www.youtube.com/watch?v=2IxoWVjsphc)\n\n\n\n**What Is Earned Value? (Ricardo Vargas) - looking ahead to project control:** [https://www.youtube.com/watch?v=x0EgZnXdunw](https://www.youtube.com/watch?v=x0EgZnXdunw)\n",
    "supporting": [
      "09-Cost-Estimation-and-Budgeting_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}